### PR TITLE
Support native async functions (node 7.6+)

### PR DESCRIPTION
**Pull request by alexeyraspopov**
Long story short:
```
~
λ node --version
v7.7.1
~
λ node
> Object.prototype.toString.call(async function(){})
'[object AsyncFunction]'
```

### CODE REVIEW

**Comment by alexeyraspopov** [comment]
I signed it!

**Comment by alexeyraspopov** [comment]
@sjelin, could you please review?

**Comment by alexeyraspopov** [comment]
Anyone from Protractor team can review this please? @juliemr @cnishina

**Comment by alexeyraspopov** [comment]
Worth mentioning, this is urgent since WebDriver's promise manager will be deprecated soon:
https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs#moving-to-asyncawait

**Comment by arielserafini** [comment]
+1 for this. Any updates?

**Comment by heathkit** [comment]
Thanks for the fix!

**Comment by renehamburger** [comment]
Thanks for this! Would be great to add a new release to get this update into protractor.

**Comment by Idooran** [comment]
I signed it!

**Pull request merged**
